### ISSUE TITLE
Enter on numpad is equal to space

### ISSUE THREAD

**Issue by Andrej123456789** [StjepanBM1/PekOS#4]
Everything is in title

**Comment by StjepanBM1** [comment]
Please answer the following questions

1 - What PekOS Version
2 - Photo if possible

**Comment by Andrej123456789** [comment]
Version - PekOS-7-1-Service-Pack

**Comment by StjepanBM1** [comment]
Well pressing stuff on numpad will display random characters and I am aware of that, PekOS 7.x Versions (at least for now) don't support numpad, insted use the normal numbers below function keys.

**Comment by Andrej123456789** [comment]
Well I hope it will come soon

**Comment by Andrej123456789** [comment]
Can you hurry up this a little bit

**Comment by StjepanBM1** [comment]
FYI (for your information) PekOS is on a pause (like my other personal projects). My hiatus will end on 31.7.2022.
Then I will come back to your issue. I hope this resolves any misunderstanding. Considering I already told you about my hiatus.

**Comment by Andrej123456789** [comment]
You said your are on haitus from social medias and you said GitHub isn't social media. If you simply don't want develop PekOS anymore that is fine but don't try find excuses. Anyway I hope you will fix in August this year

**Comment by StjepanBM1** [comment]
FYI, I'm developing PekOS during my haitus.
That is the reason why I have so many commits in private repos

**Comment by Andrej123456789** [comment]
Just fix this issue after hiatus which as you said should finished 31st July 2022

**Comment by StjepanBM1** [comment]
Well, I will.

**Comment by StjepanBM1** [comment]
Sorry for the disappointment. But this issue won't be fixed. I'm focusing on PekOS 8.

Once again sorry for the disappointment.

**Comment by Andrej123456789** [comment]
Ok

**Comment by Andrej123456789** [comment]
At least fix numpad in PekOS 8
